---
title: Component API
book: userguide
chapter: form-components
slug: component-api
weight: 210
---
<p>Form components directly translate to a resource property on the API that is generated for the form. By default a property name is generated by camel casing the field title. You can change the property name by going to the API tab in the form component settings.</p>
<img src="/assets/img/form-component-api.png">
